name: Publish NuGet package

on:
  release:
    types: [published]

jobs:
  nuget-publish:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.1.0
      with:
        source-url: https://api.nuget.org/v3/index.json
        dotnet-version: 6.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish
      run: |
        cd Recaptcha.Verify.Net
        dotnet pack -c Release -o out --no-restore
        cd out
        dotnet nuget push "*.nupkg" --skip-duplicate --api-key ${{secrets.NUGET_TOKEN}}
